[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pystabilizer"
version = "0.0"
authors = [{name = "M-Labs"}]
description = "Python utilities for the Sinara 8452 Stabilizer"
license = {text = "GPLv3"}
dependencies = [
    "pyqtgraph >= 0.13.7",
    "pyqt6 >= 6.7.0",
    "qasync >= 0.27.1",
    "pglive >= 0.7.2",
]

[project.gui-scripts]
stabilizer_control_panel = "pystabilizer.control_panel:main"

